name: ecommerce_app
description: A new Flutter e-commerce project using GetX and Isar
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6

  isar: ^3.1.0+1
  isar_flutter_libs: any

  path_provider: ^2.1.2

  uuid: ^4.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  isar_generator: ^3.1.0
